# Theme Settings
remote_theme: 'mmistakes/minimal-mistakes@4.24.0'
minimal_mistakes_skin: 'default'

# Site Settings
locale: 'ko-KR'
title: 'Inside Jinseok'
subtitle: ''
name: 'Jinseok Ock'
description: '개발 블로그입니다'
url: 'https://JJOK97.github.io'
baseurl: ''
repository: 'JJOK97/JJOK97.github.io'

# Site Author
author:
    name: 'Jinseok Ock'
    avatar: '/assets/imgs/profile.png'
    bio: '개발자입니다'
    location: 'South Korea'

# Reading Files
include:
    - _pages

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-gist
    - jekyll-feed
    - jekyll-include-cache

# Defaults
defaults:
    # _posts
    - scope:
          path: ''
          type: posts
      values:
          layout: single
          author_profile: true
          read_time: true
          comments: true
          share: true
          related: true
    # _pages
    - scope:
          path: '_pages'
          type: pages
      values:
          layout: single
          author_profile: true
